/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'elumpkin' at '1/6/16 11:40 AM' with Gradle 2.9
 *
 * @author elumpkin, @date 1/6/16 11:40 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
